benchmark:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 11.0.100-preview.4.26230.115
    
    - name: Run Benchmarks
      working-directory: ./Benchmark
      run: |
        dotnet run -c Release -- --filter "*" --exporters github fulljson --join

    - name: Upload Benchmark Artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: ./Benchmark/BenchmarkDotNet.Artifacts/results/
        retention-days: 365

    - name: Download Benchmark Artifact
      if: github.event_name == 'pull_request'
      uses: dawidd6/action-download-artifact@v8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: meshmq.yml
        branch: main
        workflow_conclusion: success
        name: benchmark-results
        path: ./Benchmark/BenchmarkDotNet.Artifacts/baseline/

    - name: Compare Benchmarks
      if: github.event_name == 'pull_request'
      working-directory: ./Benchmark
      shell: pwsh
      run: |
        ./Scripts/Compare-Benchmarks.ps1 `
          -BenchmarkPath    "./BenchmarkDotNet.Artifacts/results/" `
          -BaselinePath     "./BenchmarkDotNet.Artifacts/baseline/" `
          -ComparisonResult "./BenchmarkDotNet.Artifacts/results/comparison.md" `
          -Display `
            "key=Statistics.Mean&name=Duration&threshold=1.2", `
            "key=Memory.BytesAllocatedPerOperation&name=Allocation&threshold=1.2"

    - name: Post Benchmark Comparison (Sticky)
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v3
      with:
        file-path: ./Benchmark/BenchmarkDotNet.Artifacts/results/comparison.md # Updated path
        comment-tag: benchmark-summary
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}